#!/bin/bash
function normalize() {
# create sub-folder for output
mkdir -p normalized-images

# Begin for loop to cycle through images in queue folder
for picture in *;
do


# Normalize image sizes types and save in the new folder
if [[ $picture == *.jpg ]]; then
picture=${picture%.*};
convert $picture.jpg -resize "600>" $picture.png
echo "picture:  $picture"

elif [[ $picture == *.jpeg ]]; then
picture=${picture%.*};
convert $picture.jpeg -resize "600>" $picture.png
echo "picture:  $picture"

elif [[ $picture == *.gif ]]; then
picture=${picture%.*};
convert $picture.gif -resize "600>" $picture.png
echo "picture:  $picture"

elif [[ $picture == *.png ]]; then
picture=${picture%.*};
convert $picture.png -resize "600>" $picture.png
echo "picture:  $picture"

else
echo "file wasn't jpg, jpeg, gif, or png. either this is an error or you need to extend this script"

fi

done
}